/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.clientes.vista;

import co.unicauca.clientes.modelo.ClientesDB;
import java.util.Observable;

/**
 *
 * @author Administrador
 */
public class GUIEstadisticaPorSexoGrafica extends javax.swing.JFrame implements java.util.Observer{

    /**
     * Creates new form GUIEstadisticaPorSexoGrafica
     */
    public GUIEstadisticaPorSexoGrafica(int h, int v) {
        initComponents();
        setLocation(h, v);
        setVisible(true);
        jProgressBarHombre.setVisible(false);
        jProgressBarMujer.setVisible(false);
        jLabelHom.setVisible(false);
        jLabelMuj.setVisible(false);
    }
    
    @Override
    public void update(Observable obs, Object obj) {
        ClientesDB cliDB = (ClientesDB) obs;
        this.setTitle("Profesión: " + cliDB.getProfesion());
        graficar(cliDB.getTotalHombres(), cliDB.getTotalMujeres());
    }
    
    private void graficar(int totalHombres, int totalMujeres) {
        jProgressBarHombre.setVisible(true);
        jProgressBarMujer.setVisible(true);
        jLabelHom.setVisible(true);
        jLabelMuj.setVisible(true);
        double total = totalHombres+totalMujeres;
        double porH ;
        double porM ;
        porH = (totalHombres/total)*100;
        porM = (totalMujeres/total)*100;
        jLabelPorsentajeH.setText(""+String.format("%.2f", porH)+"%");
        jLabelPorsentajeM.setText(""+String.format("%.2f", porM)+"%");
        jProgressBarHombre.setMaximum((int)total);
        jProgressBarMujer.setMaximum((int)total);
        jProgressBarHombre.setValue(totalHombres);
        jProgressBarMujer.setValue(totalMujeres);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jProgressBarHombre = new javax.swing.JProgressBar();
        jProgressBarMujer = new javax.swing.JProgressBar();
        jLabelHom = new javax.swing.JLabel();
        jLabelMuj = new javax.swing.JLabel();
        jLabelPorsentajeH = new javax.swing.JLabel();
        jLabelPorsentajeM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBarHombre.setForeground(new java.awt.Color(255, 0, 0));
        jProgressBarHombre.setOrientation(1);
        jProgressBarHombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jProgressBarHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 69, 50, -1));

        jProgressBarMujer.setForeground(new java.awt.Color(255, 0, 0));
        jProgressBarMujer.setOrientation(1);
        jProgressBarMujer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jProgressBarMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 69, 50, -1));

        jLabelHom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelHom.setText("Hombres");
        jPanel2.add(jLabelHom, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 232, 50, -1));

        jLabelMuj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMuj.setText("Mujeres");
        jPanel2.add(jLabelMuj, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 50, 22));
        jPanel2.add(jLabelPorsentajeH, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 44, 50, 19));
        jPanel2.add(jLabelPorsentajeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 19));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEstadisticaPorSexoGrafica(400,400).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelHom;
    private javax.swing.JLabel jLabelMuj;
    private javax.swing.JLabel jLabelPorsentajeH;
    private javax.swing.JLabel jLabelPorsentajeM;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBarHombre;
    private javax.swing.JProgressBar jProgressBarMujer;
    // End of variables declaration//GEN-END:variables

    

    
}
